name = "chetaibi-municipality"
compatibility_date = "2024-12-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "chetaibi-db"
database_id = "88deecc8-4c2f-4bdb-8b1f-dba6dcaef585"

[vars]
ADMIN_USERNAME = "admin"
JWT_SECRET = "xK9mP2vR7nB4wQ8jL5sT1yF6hN3cA0dE"
